### ISSUE TITLE
Window enlarges automatically, but does not shrink

### ISSUE THREAD

**Issue by VedVid** [thindil/steamsky#37]
**Describe the bug**
Window enlarges automatically to fit all supposed text at once, but it doesn't shrink to fit lesser amount of content.

**To Reproduce**
1. Start new game, go to character creation menu
2. Change character faction to Pirates (or Undead, or Drones)
2a. Window will enlarge to fit two "info" boxes
3. Change character faction back to Poleis
3a. Window will remain enlarged, with big field of unused space

**Expected behavior**
If window enlarges automatically to fit "info" boxes, I'd expect it to shrink when these boxes are small again.

**Technical Info:**
OS: Windows 10 x64
Version: 3.0.3

**Additional context**
![image](https://user-images.githubusercontent.com/16949680/51087908-945a8800-1759-11e9-916b-09e190b489a6.png)
->
![image](https://user-images.githubusercontent.com/16949680/51087928-f0bda780-1759-11e9-9d14-e2d9e4443f92.png)
->
![image](https://user-images.githubusercontent.com/16949680/51087994-bd2f4d00-175a-11e9-8be2-c96126e60bc7.png)

**Comment by thindil** [comment]
And hello again :)
This may be a bit harder to fix, but we will see :) I hope I can fix it in few days.

**Comment by thindil** [comment]
About this: probably fixing #36 was fixed it too, simply by stopping new game window from auto resizing :) As always, thanks for the report and if you encounter this same bug again (or you disagree that this is fixed) feel free to reopen this issue or create new :)
By fixing: I mean it will be fixed in next stable release 3.0.4 and later :)
