### ISSUE TITLE
Building with build.sh does not appear to work right.

### ISSUE THREAD

**Issue by Asmageddon** [thindil/steamsky#45]
Namely, after building using `./build.sh release`, `./run.sh` does not work - the script finds neither `gtkada-env.sh`, nor `steamsky` in the folder it enters, with the former file not found in the repository directory at all, and the latter being placed in `./etc/bin` rather than `./bin`, and not runnable directly.

Furthermore, it would be nice if the script were to first run a manual check of prerequisite packages being installed one way or another, as well as instructions for building an AppImage.

**Comment by thindil** [comment]
Generally, this bug is in the documentation - `run.sh` should be used only on debug builds. It is only for development. Probably building of the release should be expanded to build whole AppImage to avoid confusion, but this is bit complicated. Additionally, I plan to replace whole this scripts with my other project (Bob) soon.

**Comment by Asmageddon** [comment]
Oh, I see. So how would one run a `./build.sh release' build, then?

**Comment by thindil** [comment]
After successful run `./build.sh release` you can copy back file `usr/bin/steamsky` to `bin` and then script `run.sh` should works. But for you it can't find whole GTKAda (this is why it scream for `gtkada-env.sh` - it should be included in GTKAda).

**Comment by Asmageddon** [comment]
So I guess that's just not included in Debian repository's builds of GTKAda, damn. So much for me wanting to skip figuring out how to make the whole thing work without downloading the GTKAda build you link in the readme :F

**Comment by thindil** [comment]
Yes, thats true. I was trying to find it in any Debian package but got zero results. Hard way solution: you can try to edit `run.sh` script and manually set path to libraries, configuration files etc. Long way solution: I should now have reason to set up Travis CI :) Other solution, you can use docker image: `thindil/gnat-gtkada` it contains everything what is needed to build the game, without polluting system with alien software ;)

**Comment by thindil** [comment]
About feedback: yes, definitely needed :) 
And if you have build binary, you can always do it in second way - decompress AppImage, put new `steamsky` binary instead of old and run it everything via `AppRun` script. Ok, then I see this issue will need two steps:
1. Create Travis CI version to simply put proper files in AppImage/Windows installation directory.
2. Clarification in README.md that `run.sh` works only on debug builds.

**Comment by thindil** [comment]
And this should be fixed too. About Travis CI - at this moment it was added only to development version. If everything will be working properly, will be added to the stable version too. Same as usual: thank you very much for your report and of course, I'm sorry for problems.

**Comment by Asmageddon** [comment]
@thindil Nice, that's awesome :)

Btw, I'm still cooking up some feedback to send your way, but... ugh I'm not really a functional person and doing things and so on can be hard t.t

**Comment by thindil** [comment]
No problem and no hurry :) We have a lot of time for feedback :)
