### ISSUE TITLE
Transferring items to ship cargo from crew member without any items

### ISSUE THREAD

**Issue by Lars-Dahl** [thindil/steamsky#59]
I guess the title says it all.

Ok, who would press the button if there are no item selected?
Well, as the curious type I am, I did press that button to see what happens.
And crash!

**Comment by thindil** [comment]
Hello :)

Thank you very much for the report. And because fun is not allowed here, I will remove this bug as soon as possible - probably tomorrow :) And good news - tomorrow will be also released a new stable version of the game thus this fix will be very fast available. Your curiosity should be safe (at least in this situation) :)

**Comment by Lars-Dahl** [comment]
And a little wish:
In the school it would be nice have the skill trained re-selected after training it.
That allow for taking several lessons in the same skill without having to select it over and over again manually. (Not really a bug - just annoying!)

**Comment by thindil** [comment]
Good that you reminded it ;) I should add this to the Wish List just don't know when I will add this to the game.

**Comment by thindil** [comment]
This also should be fixed now, so also thank you very much for the report and I'm sorry for the problems. New version of the game should be available very soon. If this bug happens again, feel free to reopen issue or create a new.
