### ISSUE TITLE
Game crashed when trying to travel to location.

### ISSUE THREAD

**Issue by ChrisEdBurt** [thindil/steamsky#74]
**Describe the bug**
Game crashed when travelling to quest location.

**To Reproduce**
Steps on how to reproduce the behavior:
1. Accept quest to destroy ship
2. Open knowledge menu
3. Set destination for quest location
4. Clicked travel to button in bottom right corner.
5. Game crashed.

**Additional context**
One other thing that I am curious about is that why during combat when I change my ship settings like speed, firing options go closer/evade, etc.. do they change after get into a new combat. I should set it once and the setting should stay, correct?
[error.log](https://github.com/thindil/steamsky/files/6080282/error.log)

**Comment by thindil** [comment]
Hello here too, and also thank you for the report.

Looks like this happens when engines are damaged during the fly (thus not exactly related to the missions, one good thing :smile:) Anyway, this one should be fixed very soon.

And yes, the game should remember the setting, this is also a bug (I forgot to add it during updating UI). Also, should be fixed very soon. :smile: Thank you for the report too.

**Comment by thindil** [comment]
Ok, it was really **very** soon :smile: Now it should be fixed in nightly version (which will be available in around a few minutes). 

As usual, thank you for the report again. If you have any question or the bug appears again, feel free to reopen this issue or create new.
