### ISSUE TITLE
Game crashed after combat

### ISSUE THREAD

**Issue by ChrisEdBurt** [thindil/steamsky#75]
**Describe the bug**
After wining a combat encounter, the game crashed.

**To Reproduce**
Steps on how to reproduce the behavior:
1. Win combat.
2. Game crashed.
[error.log](https://github.com/thindil/steamsky/files/6080301/error.log)

**Comment by thindil** [comment]
Hello, as usual thank you for the report, and I'm sorry for the problem. Just a few questions :smile: 

1. This happens after every fight?
2. It happens after the first fight or after some time of playing?
3. What exactly character you play? I mean faction and career.

At this moment this bug is very stubborn and don't want to appear for me. But I hope I can fix it in this week.

**Comment by ChrisEdBurt** [comment]
It happens randomly. 
I did the fight and it crashed, tried it again and it didn’t crash. 

It was the first fight, but it has also happened in other fights too. 

Faction, umm... default faction, i can’t remember sorry. 
My starting base was agricultural, that is also where I got the mission from. 
Career is general.

**Comment by thindil** [comment]
Ah I see, now I know why this escaped me :grin: Ok, thanks for the answers I will try to fix.

**Comment by thindil** [comment]
Ok, I think this one should be fixed now too. Thank you again for the report :smile:

Of course, if it isn't fixed, feel free to reopen this issue or create new.

**Comment by ChrisEdBurt** [comment]
Thanks for getting to it, ill take a look when I get a chance :)
