### ISSUE TITLE
Error when using mousewheel

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#77]
**To Reproduce**
Steps on how to reproduce the behavior:
1. Enter a new game.
2. Use mouse wheel.

[ClosedBraceError.log](https://github.com/thindil/steamsky/files/7245128/ClosedBraceError.log)

**Technical Info:**
 - OS: Windows
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello, thank you for the report and as usual, I'm sorry for the problem.

Yes, I can confirm the bug, it was escaped me because this bug is only on Windows, and I'm lazy and test only on Linux. :) I will try to fix it in the next days, but I'm afraid, the new release will have to wait until the next Sunday.

**Comment by thindil** [comment]
Ok, I finally started fixing the bugs. :) This one should be good now. Thank you again for the report. If you disagree or the errors will appear again, you can always reopen the issue or create a new one.

And I'm back to fixing. :)
