### ISSUE TITLE
Scrolling: Extremely Tedious

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#80]
**Describe the bug**
Mousewheel does not manipulate the scrollbar.

**Expected behavior**
Using mousewheel will scroll up and down within menus.

**Technical Info:**
 - OS: Windows
 - Version: 6.0.9

**Comment by thindil** [comment]
Hello again ;)

Hm, here is a small problem. That behavior is from used by the game graphical library. I found a workaround for it, in the development version of the game, just due to the amount of changes it cannot be ported to the stable version. I'm not sure, I will leave it open for now, and probably close it with the next big stable release (7.0).

Of course, thank you for the report. :)

**Comment by thindil** [comment]
I think it is finally fixed/implemented in the development version of the game. Thus, it can be closed for now. As always, if the problem will be still here, feel free to comment the issue or open a new one.
