### ISSUE TITLE
Pressing and Holding Movement Keys Causes Unanimated Movement

### ISSUE THREAD

**Issue by Abstrusle** [thindil/steamsky#90]
**Describe the bug**
I noticed whilst moving that if I continually press any movement key, the ship appears to lag and spontaneously appear multiple tiles away, rather than moving normally. This creates difficulty while moving quickly, as you cannot predict where your ship will appear.

**Technical Info:**
 - OS: Windows 10
 - Version: 6.0.10

**Comment by thindil** [comment]
Hello and thank you for the report again.

Personally, I'm using the mouse for that kind of movement, that's why it is moving in that way. 😄 And I also need some help. How it *should* work? I'm thinking about adding some pause between each movement during holding the key. Just this can be a bit complicated and will not arrive too soon in the development version of the game.

**Comment by thindil** [comment]
Better late than never. 😄 I did some tests with the newest stable version (7.0.5) and it looks like it is fixed. If this is not a problem, can someone check it too? Thanks in advance. 😄

**Comment by thindil** [comment]
Looks to me as fixed, I close it. If someone has the same problem, please reopen it or create a new issue. Thank you for reporting. :smile:
