### ISSUE TITLE
Can't launch 7.9

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#94]
I downloaded steamsky-7.9-dev-64.zip and extracted it. When I run steamsky.exe, I briefly get a loading spinner and then nothing happens. No window or console is ever launched. I am running Windows 11 Pro.

Here is the error log:

> 2022-10-20 02:03:56.00
> Version: 7.9
> Exception: CONSTRAINT_ERROR
> Message: bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> raised CONSTRAINT_ERROR : bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> 2022-10-20 02:04:04.00
> Version: 7.9
> Exception: CONSTRAINT_ERROR
> Message: bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> raised CONSTRAINT_ERROR : bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> 2022-10-20 02:04:17.00
> Version: 7.9
> Exception: CONSTRAINT_ERROR
> Message: bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> raised CONSTRAINT_ERROR : bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> 2022-10-20 02:04:20.00
> Version: 7.9
> Exception: CONSTRAINT_ERROR
> Message: bad input for 'Value: "fullSpeed"
> -------------------------------------------------
> raised CONSTRAINT_ERROR : bad input for 'Value: "fullSpeed"
> -------------------------------------------------
>

**Comment by thindil** [comment]
Hello and thank you for the report.

If I remember correctly, I found this bug one or two days after release of 7.9. My bad that I didn't mention it earlier. It is fixed in the recent nightly builds of the game. It happens when there is no file `game.cfg` in *saves* directory. There are two ways to fix or workaround it:

1. Copy directory *saves* from the stable version of the game to the development version.
2. Use one of the recent nightly builds from here: https://github.com/thindil/steamsky/actions/workflows/ada-devel.yml

The preferred way is to use nightly versions as they contain some bug fixes, thus can be more stable than the version 7.9. They don't contain needed libraries, thus have to be extracted to the same directory where version 7.9 is. I think, this part of the documentation can help in that matter: https://github.com/thindil/steamsky#testing-versions If you have any questions about it, feel free to ask.

I will leave this report open until release of 8.0 and pin it, so other people should easier find the solution for the problem. 😉

**Comment by rmvgaines** [comment]
Thank you. This resolved the problem.

**Comment by thindil** [comment]
As the version 8.0 arrived, I unpinned and close the issue. Again, thank you for the report.
