### ISSUE TITLE
Ability to clear Numeric Fields

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#95]
When buying, selling, etc. it should be possible to clear the field before entering a number. As an example, if I click the sell button the numeric field is pre-populated with the number 1. If I want to buy 25 and immediately type in "25", the field reads "125". This is not a huge issue, but the bigger problem comes into play when I use the backspace key. For example, If I enter the selling field and hold down the backspace key, presumably to clear the field, before I enter a number I still get the preceding 1 in front of the number I enter. The problem can be observed in the video I linked in another issue. The issue is still present in the nightly build.

**Comment by thindil** [comment]
Hello, as usual, thank you for the report.

Yes, entering numbers in forms needs some love. I'm marking it as an enhancement, but we will see, maybe I will be able to do something with it before 8.0 release.

**Comment by rmvgaines** [comment]
Thank you for all of the work that you put into this project! For me, this is probably the most problematic "non-bug" in the game.

**Comment by thindil** [comment]
Better late than never. 😉 Unfortunately, I wasn't able to add this to the 8.0 version, but it now landed in the development version of the game. The feature will be available from version 8.1. It took some time, because I also added blocking proper action buttons, like for example "Buy" button when the fields are empty.

Again, thank you for the suggestion. And now I back to add another and fixing bugs. 😄
