### ISSUE TITLE
Enhancement: Display Fuel, Food, and Water on Map View

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#97]
Since at least half of the game is spent on the map view, it would be convenient to display fuel, water, and food supplies on this view. Perhaps at the top of the screen? This would reduce the need to go into the ship's inventory view.

**Comment by thindil** [comment]
Hello, and as always, thank you for the idea. 😄 

I like it and I think I could implement it. Just it will need to wait "a bit". The first thing I want to do with the next version, is to back and finish the player's ship's crew management UI. There is still some work to do. I don't know how long it will take me to implement all the ideas which I have there.

Additionally, I need to think about how that information present to the player. Maybe instead of amounts there will be better to show info like food for 6 days, drinks for 10, etc.? I will think about it when I start working on it, but any suggestions, even now, are welcome.

**Comment by rmvgaines** [comment]
"player's ship's crew management UI" - I will admit that I find the current interface/behavior to be a bit confusing. 

"Maybe instead of amounts, there will be better to show info like food for 6 days, drinks for 10, etc.?" - My only concern with this is: What if you add status effects later on that change consumption? Also, it might get a bit confusing when hiring new crew. Maybe show the resource total, current consumption, and estimated number of days?

**Comment by thindil** [comment]
Let's hope that the new version will be less confusing. 😉 

Amount, I'm trying to keep it simple, thus probably just amount instead of days. Adding too much information can also be overwhelming. I need to think about it. Additionally, there can always be a space for some of the game's modifications. 😄

**Comment by rmvgaines** [comment]
“Simplicity is the ultimate sophistication” – Leonardo da Vinci.

**Comment by thindil** [comment]
Another necro in action. 😉 I added it to the development version of the game. I selected your proposition, showing the things' amount. Again, thank you for the suggestion.
