### ISSUE TITLE
raised CONSTRAINT_ERROR : dialogs.adb:375 range check failed in v8.0

### ISSUE THREAD

**Issue by rmvgaines** [thindil/steamsky#98]
v8.0 crashed on Windows 11 after attempting to drag the "buy" popup with the mouse on the trade menu.
[saves.zip](https://github.com/thindil/steamsky/files/9925408/saves.zip)

**Comment by thindil** [comment]
Hello and thank you for the report. I will look at it and try to fix it as soon as possible.

**Comment by thindil** [comment]
I think I fixed this one now. 😉 The problem is, that I couldn't reproduce the bug. Fortunately, you bring enough information to at least try to fix it. You can check if it is fixed, without waiting for the next stable release, by using the nightly version of the game. I will wait one more week, and create a new release on the next Sunday. Maybe I will be able to find more things to fix. If the problem will still persist, feel free to add a comment here or create a new report.

Thank you very much for the report, and I'm sorry for the issue.

**Comment by rmvgaines** [comment]
Honestly, I can't seem to reproduce it on the current release. It happened once and then hasn't happened again. I have even attempted to duplicate it step-by-step from my last save.

**Comment by thindil** [comment]
Yes, I can't reproduce it too. 😄  I'm not sure what caused it, maybe some bug in one of the libraries used by the game. I added better checks to the code, so if it happens again, it will just stop dragging the dialog but not crash the whole game.
